// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDi9raYCKw6OzFlphxj4zf-UoeBLb7-M',
    appId: '1:482975689021:web:a70f7b269944dd94027d54',
    messagingSenderId: '482975689021',
    projectId: 'usersgraduation',
    authDomain: 'usersgraduation.firebaseapp.com',
    storageBucket: 'usersgraduation.appspot.com',
    measurementId: 'G-QVXXRJ2Q9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHCmoLPlB3eT_vRnNiyzd9qZIRs1fiz8',
    appId: '1:482975689021:android:983f7e705902a7bd027d54',
    messagingSenderId: '482975689021',
    projectId: 'usersgraduation',
    storageBucket: 'usersgraduation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWyMzMzAL65pm9gHwDPpjaALgxcpoLBE',
    appId: '1:482975689021:ios:be53755365b120ff027d54',
    messagingSenderId: '482975689021',
    projectId: 'usersgraduation',
    storageBucket: 'usersgraduation.appspot.com',
    iosClientId: '482975689021-ptn2s5phd3u01kihkd1tphqq39s2l4o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersGradution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWyMzMzAL65pm9gHwDPpjaALgxcpoLBE',
    appId: '1:482975689021:ios:67a1cc94f0e0f767027d54',
    messagingSenderId: '482975689021',
    projectId: 'usersgraduation',
    storageBucket: 'usersgraduation.appspot.com',
    iosClientId: '482975689021-5edk49rl55m47jj5shikclr2m9ppkpgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersGradution.RunnerTests',
  );
}
