// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsETUe5wNAr2y9Ut4Q-yDLvV5lS1rnLU',
    appId: '1:128453386180:web:60649f684020e497188e91',
    messagingSenderId: '128453386180',
    projectId: 'graduationapplica',
    authDomain: 'graduationapplica.firebaseapp.com',
    storageBucket: 'graduationapplica.appspot.com',
    measurementId: 'G-3MHLQ36E7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonJ0z1DdvjV0ate24rWVqQHqrf9UN69g',
    appId: '1:128453386180:android:4d31d422bf749cf2188e91',
    messagingSenderId: '128453386180',
    projectId: 'graduationapplica',
    storageBucket: 'graduationapplica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtkZu-OeQ9e6pZfFlgxOpbTpC3SqnjUhs',
    appId: '1:128453386180:ios:9c358ce58512da6d188e91',
    messagingSenderId: '128453386180',
    projectId: 'graduationapplica',
    storageBucket: 'graduationapplica.appspot.com',
    iosClientId: '128453386180-hrnug2juco5l4mb8o9l13cvm6g7565ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradutionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtkZu-OeQ9e6pZfFlgxOpbTpC3SqnjUhs',
    appId: '1:128453386180:ios:a10a796f67502d86188e91',
    messagingSenderId: '128453386180',
    projectId: 'graduationapplica',
    storageBucket: 'graduationapplica.appspot.com',
    iosClientId: '128453386180-bcfacmq1qhtid59amtqg0lqlbjqjsprk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradutionApp.RunnerTests',
  );
}
