// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfPGoe7x10vcS1nkGk2B0nzGTVz9DZ1TQ',
    appId: '1:854098827618:web:92efb384e20724809c343b',
    messagingSenderId: '854098827618',
    projectId: 'ridersapp-c1273',
    authDomain: 'ridersapp-c1273.firebaseapp.com',
    storageBucket: 'ridersapp-c1273.appspot.com',
    measurementId: 'G-E56MD1YL08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGu_lxh2hg7rZv2KE2zSK3xjc1BXZHSck',
    appId: '1:854098827618:android:bece72091f963b579c343b',
    messagingSenderId: '854098827618',
    projectId: 'ridersapp-c1273',
    storageBucket: 'ridersapp-c1273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qBmY3afg94jndic3otryJPfKoGqRhBI',
    appId: '1:854098827618:ios:d5b46531a7283f479c343b',
    messagingSenderId: '854098827618',
    projectId: 'ridersapp-c1273',
    storageBucket: 'ridersapp-c1273.appspot.com',
    iosClientId: '854098827618-snjbieiub2rls3dg8gsm1u1q481ocsk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5qBmY3afg94jndic3otryJPfKoGqRhBI',
    appId: '1:854098827618:ios:5aa072595ac385bd9c343b',
    messagingSenderId: '854098827618',
    projectId: 'ridersapp-c1273',
    storageBucket: 'ridersapp-c1273.appspot.com',
    iosClientId: '854098827618-epdjlo2vkckadoa775q2ls3fvsvnscni.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridersApp.RunnerTests',
  );
}
